nelmio_api_doc:
    documentation:
        info:
            title: Job Listing API
            description: API for job listings and applications
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$) 